FROM python:3.9-slim

WORKDIR /app

COPY streamlit_app.py .

RUN apt-get update && apt-get install -y netcat-openbsd

RUN pip install streamlit kafka-python

CMD ["sh", "-c", "while ! nc -z kafka 9092; do sleep 1; done; streamlit run streamlit_app.py"]
